/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ApplicationTagCreateNestedManyWithoutApplicationsInput } from "./ApplicationTagCreateNestedManyWithoutApplicationsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { ApplicationVersionCreateNestedManyWithoutApplicationsInput } from "./ApplicationVersionCreateNestedManyWithoutApplicationsInput";
import { PageCreateNestedManyWithoutApplicationsInput } from "./PageCreateNestedManyWithoutApplicationsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumApplicationStatus } from "./EnumApplicationStatus";

@InputType()
class ApplicationCreateInput {
  @ApiProperty({
    required: false,
    type: () => ApplicationTagCreateNestedManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => ApplicationTagCreateNestedManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => ApplicationTagCreateNestedManyWithoutApplicationsInput, {
    nullable: true,
  })
  applicationTags?: ApplicationTagCreateNestedManyWithoutApplicationsInput;

  @ApiProperty({
    required: false,
    type: () => ApplicationVersionCreateNestedManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => ApplicationVersionCreateNestedManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => ApplicationVersionCreateNestedManyWithoutApplicationsInput, {
    nullable: true,
  })
  applicationVersions?: ApplicationVersionCreateNestedManyWithoutApplicationsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => PageCreateNestedManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => PageCreateNestedManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => PageCreateNestedManyWithoutApplicationsInput, {
    nullable: true,
  })
  pages?: PageCreateNestedManyWithoutApplicationsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  screenshot?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumApplicationStatus,
  })
  @IsEnum(EnumApplicationStatus)
  @IsOptional()
  @Field(() => EnumApplicationStatus, {
    nullable: true,
  })
  status?: "Option1" | null;
}

export { ApplicationCreateInput as ApplicationCreateInput };
