/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ApplicationTagUpdateManyWithoutApplicationsInput } from "./ApplicationTagUpdateManyWithoutApplicationsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { ApplicationVersionUpdateManyWithoutApplicationsInput } from "./ApplicationVersionUpdateManyWithoutApplicationsInput";
import { PageUpdateManyWithoutApplicationsInput } from "./PageUpdateManyWithoutApplicationsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumApplicationStatus } from "./EnumApplicationStatus";

@InputType()
class ApplicationUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ApplicationTagUpdateManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => ApplicationTagUpdateManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => ApplicationTagUpdateManyWithoutApplicationsInput, {
    nullable: true,
  })
  applicationTags?: ApplicationTagUpdateManyWithoutApplicationsInput;

  @ApiProperty({
    required: false,
    type: () => ApplicationVersionUpdateManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => ApplicationVersionUpdateManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => ApplicationVersionUpdateManyWithoutApplicationsInput, {
    nullable: true,
  })
  applicationVersions?: ApplicationVersionUpdateManyWithoutApplicationsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => PageUpdateManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => PageUpdateManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => PageUpdateManyWithoutApplicationsInput, {
    nullable: true,
  })
  pages?: PageUpdateManyWithoutApplicationsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  screenshot?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumApplicationStatus,
  })
  @IsEnum(EnumApplicationStatus)
  @IsOptional()
  @Field(() => EnumApplicationStatus, {
    nullable: true,
  })
  status?: "Option1" | null;
}

export { ApplicationUpdateInput as ApplicationUpdateInput };
