/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Application as PrismaApplication,
  ApplicationTag as PrismaApplicationTag,
  ApplicationVersion as PrismaApplicationVersion,
  Page as PrismaPage,
} from "@prisma/client";

export class ApplicationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ApplicationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.application.count(args);
  }

  async applications(
    args: Prisma.ApplicationFindManyArgs
  ): Promise<PrismaApplication[]> {
    return this.prisma.application.findMany(args);
  }
  async application(
    args: Prisma.ApplicationFindUniqueArgs
  ): Promise<PrismaApplication | null> {
    return this.prisma.application.findUnique(args);
  }
  async createApplication(
    args: Prisma.ApplicationCreateArgs
  ): Promise<PrismaApplication> {
    return this.prisma.application.create(args);
  }
  async updateApplication(
    args: Prisma.ApplicationUpdateArgs
  ): Promise<PrismaApplication> {
    return this.prisma.application.update(args);
  }
  async deleteApplication(
    args: Prisma.ApplicationDeleteArgs
  ): Promise<PrismaApplication> {
    return this.prisma.application.delete(args);
  }

  async findApplicationTags(
    parentId: string,
    args: Prisma.ApplicationTagFindManyArgs
  ): Promise<PrismaApplicationTag[]> {
    return this.prisma.application
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .applicationTags(args);
  }

  async findApplicationVersions(
    parentId: string,
    args: Prisma.ApplicationVersionFindManyArgs
  ): Promise<PrismaApplicationVersion[]> {
    return this.prisma.application
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .applicationVersions(args);
  }

  async findPages(
    parentId: string,
    args: Prisma.PageFindManyArgs
  ): Promise<PrismaPage[]> {
    return this.prisma.application
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .pages(args);
  }
}
