/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ApplicationTagListRelationFilter } from "../../applicationTag/base/ApplicationTagListRelationFilter";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { ApplicationVersionListRelationFilter } from "../../applicationVersion/base/ApplicationVersionListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { PageListRelationFilter } from "../../page/base/PageListRelationFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { EnumApplicationStatus } from "./EnumApplicationStatus";

@InputType()
class ApplicationWhereInput {
  @ApiProperty({
    required: false,
    type: () => ApplicationTagListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ApplicationTagListRelationFilter)
  @IsOptional()
  @Field(() => ApplicationTagListRelationFilter, {
    nullable: true,
  })
  applicationTags?: ApplicationTagListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ApplicationVersionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ApplicationVersionListRelationFilter)
  @IsOptional()
  @Field(() => ApplicationVersionListRelationFilter, {
    nullable: true,
  })
  applicationVersions?: ApplicationVersionListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PageListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PageListRelationFilter)
  @IsOptional()
  @Field(() => PageListRelationFilter, {
    nullable: true,
  })
  pages?: PageListRelationFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  screenshot?: JsonFilter;

  @ApiProperty({
    required: false,
    enum: EnumApplicationStatus,
  })
  @IsEnum(EnumApplicationStatus)
  @IsOptional()
  @Field(() => EnumApplicationStatus, {
    nullable: true,
  })
  status?: "Option1";
}

export { ApplicationWhereInput as ApplicationWhereInput };
